name: 自動リリース用ワークフロー

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリを取得
        uses: actions/checkout@v3

      - name: 辞書生成してアーカイブ
        run: |
          DATETIME=$(date '+%Y%m%d_%H%M%S')
          echo "DATETIME=${DATETIME}" >> $GITHUB_ENV
          python ./makedict.py -g src/*.json > mozc.txt
          python ./makedict.py -g -s src/*.json > mozc_no_japanese.txt
          python ./makedict.py -m src/*.json > msime.txt
          python ./makedict.py -m -s src/*.json > msime_no_japanese.txt
          zip chmdict${DATETIME}.zip mozc.txt mozc_no_japanese.txt msime.txt msime_no_japanese.txt

      - name: リリースを作成
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.DATETIME }}
          release_name: ${{ env.DATETIME }}
          body: "生成された辞書はchmdict${{ env.DATETIME }}.zip"
          draft: false
          prerelease: false

      - name: リリースアセットをアップロード
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./chmdict${{ env.DATETIME }}.zip
          asset_name: chmdict${{ env.DATETIME }}.zip
          asset_content_type: application/zip

      - name: 最新のリリース1つ以外の古いリリースを削除
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
